
from dataclasses import dataclass

@dataclass
class PCBPriceModel:
    testfee: float = 0,
    plate: float = 0,
    clc: float =  0,
    gch: float = 0,
    bgafee: float = 0,
    impendancefee: float = 0,
    pin: float = 0,
    copperfee: float = 0,
    colorfee: float = 0,
    sprayfee: float = 0,
    extraurgentfee: float = 0,
    viasfee: float = 0,
    bankongfee: float = 0,
    utilizationfee: float = 0,
    discountfee: float = 0,
    boardfee: float = 0,
    difficultyfee: float = 0,
    coverfee: float = 0,
    blindfee: float = 0,
    pressingfee: float = 0,
    cjfee: float = 0,
    pthfee: float = 0,
    viainpadfee: float = 0,
    reportfee: float = 0,
    populerfee: float = 0,
    paperfee: float = 0,
    userstampfee: float = 0,
    acceptancefee: float = 0,
    crossfee: float = 0,
    invoicefee: float = 0,
    insurancefee: float = 0,
    zkfee: float = 0,
    cutfee: float = 0,
    luocao: float = 0,
    luocheng: float = 0,    
